[package]
name = "demand_paging"
version = "0.1.0"
edition = "2021"

[dependencies]
frame_allocator = { path = "../frame_allocator" }
halt = { path = "../halt" }
log = "0.4"
memory = { path = "../memory" }
x86_64 = "0.14"
