[package]
name = "app_io_2"
version = "0.1.0"
edition = "2021"

[dependencies]
core2 = { version = "0.4.0", default-features = false, features = [
  "alloc",
  "nightly",
] }
keycodes_ascii = { path = "../../libs/keycodes_ascii" }
mutex_sleep = { path = "../mutex_sleep" }
