[package]
name = "test_std"
version = "0.1.0"
edition = "2021"

[dependencies]
spawn = { path = "../../kernel/spawn" }
memory = { path = "../../kernel/memory" }
stack = { path = "../../kernel/stack" }