[package]
name = "condvar"
version = "0.1.0"
authors = ["Klim Tsoutsman <klim@tsoutsman.com>"]
edition = "2021"
description = "A condvar implementation"

[dependencies]
semaphore = { path = "../semaphore" }
